version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g @angular/cli
      - npm link @angular/cli
  pre_build:
    commands:
      - ng build --configuration production
artifacts:
  base-directory: 
  files:
    - 'dist/my-angular-project/**/*'
    - appspec.yml
    - 'deploy-scripts/**/*'
